api/urls.py
__author__ = 'Lei Huang'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^data_id/(?P<req_data_id>[A-Za-z0-9_]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/$', views.data, name='data'),
    #url(r'^data_id/(?P<req_data_id>[A-Za-z0-9_]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/$', views.dataDetail.as_view(), name='data'),
    #url(r'^id/(?P<id>[0-9]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/$', views.data, name='data'),
    #url(r'^heatmap/(?P<data_id>[0-9]+)/$', views.heatmap, name='heatmap'),
    url(r'^heatmap/data_id/(?P<req_data_id>[A-Za-z0-9_]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/$', views.heatmap, name='heatmap'),

    url(r'^heatmap/data_id/(?P<req_data_id>[A-Za-z0-9_]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/dim2/(?P<dim2>[ixz])/$', views.heatmap, name='heatmap'),

    url(r'^heatmap/data_id/(?P<req_data_id>[A-Za-z0-9_]+)/dim/(?P<dim>[ixz])/num/(?P<num>[0-9]+)/dim2/(?P<dim2>[ixz])/dim3/(?P<dim3>[ixz])/$', views.heatmap, name='heatmap'),

    url(r'^log/$', views.log, name='log'),
]

dataserver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from rest_framework import permissions


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

api/models.py
from django.db import models
from rest_framework import permissions

# Create your models here.
class Log(models.Model):
    permission_classes = (permissions.IsAuthenticated,)
    data_id = models.CharField(max_length=256)  # what data is accessed
    access_date = models.DateTimeField('date accessed') # what time
    action = models.CharField(max_length=100)   # what action to the data (POST/GET)
    user_id = models.CharField(max_length=100)  # who accessed the data
    command = models.CharField(max_length=512)  # command to access the data

    def __str__(self):
        return "Data: " + self.data_id + ", " + self.access_date.strftime("%m/%d/%Y %H:%M:S") + ", " + self.action + ", " + self.user_id + ", " + self.command


class DataInfo(models.Model):
    data_id = models.CharField(max_length=256)
    data_type = models.CharField(max_length=256)  #seismic, csv ...
    data_storage = models.CharField(max_length=256) # file, database, No-SQL database...
    data_location = models.CharField(max_length=512)  # file path, database info ..
    owner = models.CharField(max_length=256)  # data owner

    def __str__(self):
        return "Data: " + self.data_id + ", " + self.data_type + ", " + self.data_storage + ", " + self.data_location

api/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404, HttpResponseForbidden
from . import ReadSlice 
from api.models import *
from django.utils import timezone
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from api.permissions import *
from django.core.exceptions import PermissionDenied

from bokeh.resources import CDN
from bokeh.embed import components

from bokeh.layouts import gridplot
from bokeh.io import output_file, show

def index(request):
    return HttpResponse("Welcome to data server")

class dataDetail(APIView):
    #permission_classes = (IsOwnerOrShared,permissions.IsAdminUser,)
    queryset = DataInfo.objects.all()

    def get_object(self, req_data_id):
        try:
            return DataInfo.objects.get(data_id = req_data_id)
        except DataInfo.DoesNotExist:
            raise Http404

    def get(self, request, req_data_id, dim, num, format = None ):
        d = self.get_object(req_data_id)
        print (request.user.username, d.owner)
        if d.owner == request.user.username and request.user.is_authenticated():
            return HttpResponse(readSliceToJson(d.data_location, dim, int(num)), content_type="application/json")
        else:
            raise PermissionDenied

def data(request, req_data_id, dim, num):
    l = Log(data_id=req_data_id, access_date=timezone.now(), action='GET', user_id='unknown', command='Get '+req_data_id + ' dim ' + dim + num )
    l.save()
    # Get the file name
    try:
        d = DataInfo.objects.get(data_id = req_data_id)
    except DataInfo.DoesNotExist:
        raise Http404
    return HttpResponse(ReadSlice.readSliceToJson(d.data_location, dim, int(num)), content_type="application/json")

def heatmap(request, req_data_id, dim, num, dim2=None, dim3=None):
    l = Log(data_id=req_data_id, access_date=timezone.now(), action='GET', user_id='unknown', command='Get '+req_data_id + ' dim ' + dim + num )
    l.save()
    d = DataInfo.objects.get(data_id = req_data_id)

    p1 = ReadSlice.readSliceBokeh(d.data_location, dim, int(num), req_data_id)
    script, div = components(p1, CDN)
    
    context = {
    'id': req_data_id,
    'dim': dim,
    'num': num,
    'the_script': script,
    'the_div': div,
    }

    if dim2 != None:
        p2 = ReadSlice.readSliceBokeh(d.data_location, dim2, int(num), req_data_id)
        script2, div2 = components(p2, CDN)
        context2 = {
        'the_script2': script2,
        'the_div2': div2,
        }
        context.update(context2)


    if dim3 != None:
        p3 = ReadSlice.readSliceBokeh(d.data_location, dim3, int(num), req_data_id)
        script3, div3 = components(p3, CDN)
        context3 = {
        'the_script3': script3,
        'the_div3': div3,
        }
        context.update(context3)

    return render(request, 'data/heatmapjs.html', context)

def log(request):
    permission_classes = (permissions.IsAuthenticated,)
    latest_log_list = Log.objects.order_by('-access_date')
    context = {'log_list': latest_log_list}
    return render(request, 'data/log.html', context)

templates/data/heatmapjs.html
<!DOCTYPE html>
<html lang="en">

<link
    href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.0.min.css"
    rel="stylesheet" type="text/css">
    <link
    href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.0.min.css"
    rel="stylesheet" type="text/css">

    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.0.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.0.min.js"></script>

<head>
    <meta charset="UTF-8">
    <title>Experiment with Bokeh</title>
</head>

<body>
{{ the_div|safe }}

{{ the_script|safe }}
</body>

<body>
{{ the_div2|safe }}

{{ the_script2|safe }}
</body>

<body>
{{ the_div3|safe }}

{{ the_script3|safe }}
</body>

<head>
    <meta charset="utf-8">
    <title>Legend Example (DOM Legends) | heatmap.js</title>
    <style>
        body, html, h2 {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        body {
            font-family: sans-serif;
        }

        body * {
            font-weight: 200;
        }

        #heatmapContainerWrapper {
            width: 100%;
            height: 100%;
            position: absolute;
            background: rgba(0, 0, 0, .1);
        }

        #heatmapContainer {
            width: 100%;
            height: 100%;
        }

        #heatmapLegend {
            background: white;
            position: absolute;
            bottom: 0;
            right: 0;
            padding: 10px;
        }

        .tooltip {
            position: absolute;
            left: 0;
            top: 0;
            background: rgba(0, 0, 0, .8);
            color: white;
            font-size: 14px;
            padding: 5px;
            line-height: 18px;
            display: none;
        }

        #min {
            float: left;
        }

        #max {
            float: right;
        }

        h1 {
            position: absolute;
            background: black;
            color: white;
            padding: 10px;
            font-weight: 200;
        }

        #all-examples-info {
            position: absolute;
            background: white;
            font-size: 16px;
            padding: 20px;
            top: 100px;
            width: 350px;
            line-height: 150%;
            border: 1px solid rgba(0, 0, 0, .2);
        }
    </style>
</head>

<body>
<div id="heatmapContainerWrapper">
    <div id="heatmapContainer">
    </div>

    <div id="heatmapLegend">
        <h2>Descriptive Legend Title</h2>
        <span id="min"></span>
        <span id="max"></span>
        <img id="gradient" src="" style="width:100%"/>
    </div>
    <div class="tooltip"></div>
</div>

{% load staticfiles %}
<script src="{% static  "js/heatmap.min.js" %}"></script>
<script>
    window.onload = function () {
        // helper function
        function $(id) {
            return document.getElementById(id);
        };


        function Get(yourUrl) {
            var Httpreq = new XMLHttpRequest(); // a new request
            Httpreq.open("GET", yourUrl, false);
            Httpreq.send(null);
            return Httpreq.responseText;
        }

        var json_data = JSON.parse(Get("{% url 'api:data' id dim num%}"));
        console.log("this is the author name: " + json_data.data[1][2]);

        /*  legend code */
        // we want to display the gradient, so we have to draw it
        var legendCanvas = document.createElement('canvas');
        legendCanvas.width = 100;
        legendCanvas.height = 10;

        var legendCtx = legendCanvas.getContext('2d');
        var gradientCfg = {};

        function updateLegend(data) {
            // the onExtremaChange callback gives us min, max, and the gradientConfig
            // so we can update the legend
            $('min').innerHTML = data.min.toFixed(2);
            $('max').innerHTML = data.max.toFixed(2);
            // regenerate gradient image
            if (data.gradient != gradientCfg) {
                gradientCfg = data.gradient;
                var gradient = legendCtx.createLinearGradient(0, 0, 100, 1);
                for (var key in gradientCfg) {
                    gradient.addColorStop(key, gradientCfg[key]);
                }

                legendCtx.fillStyle = gradient;
                legendCtx.fillRect(0, 0, 100, 10);
                $('gradient').src = legendCanvas.toDataURL();
            }
        };
        /* legend code end */


        // create a heatmap instance
        var heatmap = h337.create({
            container: document.getElementById('heatmapContainer'),
            maxOpacity: .5,
            radius: 10,
            blur: .75,
            // update the legend whenever there's an extrema change
            onExtremaChange: function onExtremaChange(data) {
                updateLegend(data);
            }
        });

        var radius = 4;
        // boundaries for data generation
        var width = json_data.I * radius; //(+window.getComputedStyle(document.body).width.replace(/px/,''));
        var height = json_data.J * radius; //(+window.getComputedStyle(document.body).height.replace(/px/,''));
        var max = -65555;
        var min = 65555;

        // generate 1000 datapoints
        var generate = function () {
            // randomly generate extremas

            var t = [];
            var I = json_data.I;
            var J = json_data.J;

            for (var i = 0; i < I; i++)
                for (var j = 0; j < J; j++) {
                    var x = i * radius;
                    var y = j * radius;
                    var c = (json_data.data[i][j]);
                    if (max < c)
                        max = c;
                    if (min > c)
                        min = c
                    // btw, we can set a radius on a point basis
                    var r = radius;
                    // add to dataset
                    t.push({x: x, y: y, value: c, radius: r});
                    //if(i==0)
                    //     console.log(x,y,c);
                }
            var init = +new Date;
            // set the generated dataset
            heatmap.setData({
                min: min,
                max: max,
                data: t
            });
            //console.log('took ', (+new Date) - init, 'ms');
        };
        // initial generate
        generate();
        console.log(max, min)

        // whenever a user clicks on the ContainerWrapper the data will be regenerated -> new max & min
        document.getElementById('heatmapContainerWrapper').onclick = function () {
            generate();
        };

        var demoWrapper = document.getElementById('heatmapContainerWrapper');
        var tooltip = document.querySelector('.tooltip');

        function updateTooltip(x, y, value) {
            // + 15 for distance to cursor
            var transform = 'translate(' + (x + 15) + 'px, ' + (y + 15) + 'px)';
            tooltip.style.MozTransform = transform;
            /* Firefox */
            tooltip.style.msTransform = transform;
            /* IE (9+) - note ms is lowercase */
            tooltip.style.OTransform = transform;
            /* Opera */
            tooltip.style.WebkitTransform = transform;
            /* Safari and Chrome */
            tooltip.style.transform = transform;
            /* One day, my pretty */
            tooltip.innerHTML = value.toString();
        }

        demoWrapper.onmousemove = function (ev) {
            var x = Math.round(ev.layerX / radius) * radius;
            var y = Math.round(ev.layerY / radius) * radius;
            var value = heatmap.getValueAt({
                x: x,
                y: y
            });

            tooltip.style.display = 'block';

            updateTooltip(x, y, value);
            //  console.log(x,y,value);

        };
        demoWrapper.onmouseout = function () {
            tooltip.style.display = 'none';
        };


    };
</script>
</body>
</html>

templates/data/log.html
<h1>Log</h1>
<ul>
{% for l in log_list.all %}
    <li>Data_id: {{ l.data_id  }} Date:  {{l.access_date}} Action: {{ l.action}} User: {{l.user_id}} Command: {{l.command}}</li>
{% endfor %}
</ul>